### ISSUE TITLE
new rollouts fail due to volume mount

### ISSUE THREAD

**Issue by wadeking98** [BCDevOps/matomo-openshift#17]
reproduce:
- generate a new matomo deployment from scratch on ocp4
- once deployment has completed got o openshift console and click on matomo pod
- select start rollout from the action dropdown

result:
- rollout hangs and new container is never created
- event log throws warning ```Unable to attach or mount volumes: unmounted volumes=[matomo-config], unattached volumes=[matomo-source matomo-config default-token-vsxd2]: timed out waiting for the condition
```

**Comment by esune** [comment]
@WadeBarnes we experienced this issue yesterday when testing in OCP4, rollouts in OCP3 work properly (tested a while back when I updated the base images). Is this something known that we shoud be working around in OCP4, or is it gremlins that need further investigation?

**Comment by WadeBarnes** [comment]
Which environment?

**Comment by wadeking98** [comment]
changed
