### ISSUE TITLE
matomo-proxy swallows requests to /piwik.php, which breaks some plugins that haven't followed name change to matomo.

### ISSUE THREAD

**Issue by sheaphillips** [BCDevOps/matomo-openshift#3]
In our case, we are using gatsby, a static site generation tool/framework and the provided plugin has not fully updated its code to refer to matomo in place of piwik.  Other tools are also likely in a similar state.

The `openshift-matomo` deployment should be backwards compatible with tools that still reference piwik.php as the entrypoint for submitting browser tracking events.

**Comment by esune** [comment]
Resolved by #4
