### ISSUE TITLE
Error on deploy to openshift

### ISSUE THREAD

**Issue by Zoharos** [BCDevOps/matomo-openshift#8]
Hi, 
When I try to deploy matomo on openshift i get this error `Error: [pool www] failed to set gid(82): operation not permitted`
Thanks

**Comment by esune** [comment]
Hi @Zoharos, could you please provide additional details on:
- what version of OpenShift are you using?
- what are the steps you're following to deploy Matomo?
- I assume it is the Matomo service that is throwing that error: could you please provide more logs?

**Comment by WadeBarnes** [comment]
@Zoharos, please try the [latest release](https://github.com/BCDevOps/matomo-openshift/releases/tag/3.13.3).  If you still have a problem please enter another issue.
